version: "3.7"
services:
    nginx_proxy:
        image: nginx_https_proxy:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nginx_proxy
        ports:
            - 443:443
        volumes:
            - ./nginx.conf/nginx_whitelist.conf:/usr/local/nginx/conf/nginx.conf
        environment:
            - TZ=Etc/UTC
        restart: always